//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HelpTool.rc
//
#define IDD_HELPTOOL_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_REPORTING                   1000
#define IDC_SOURCE                      1001
#define IDC_TARGETHTML                  1002
#define IDC_TARGETDOC                   1003
#define IDC_GO                          1004
#define IDC_INCLUDES                    1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
