#if !defined(AFX_LICENSE_H__76C48DAD_0944_4E45_A944_8DFCA1DEC683__INCLUDED_)
#define AFX_LICENSE_H__76C48DAD_0944_4E45_A944_8DFCA1DEC683__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// License.h : header file
//

/////////////////////////////////////////////////////////////////////////////
// CLicense document

class CLicense : public CDocument
{
protected:
	DECLARE_DYNCREATE(CLicense)

// Attributes
public:

// Operations
public:

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CLicense)
	public:
	protected:
	//}}AFX_VIRTUAL

// Implementation
public:
	CLicense();
#ifdef _DEBUG
#endif

	// Generated message map functions
protected:
	//{{AFX_MSG(CLicense)
		// NOTE - the ClassWizard will add and remove member functions here.
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LICENSE_H__76C48DAD_0944_4E45_A944_8DFCA1DEC683__INCLUDED_)
