//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by StageRace.rc
//
#define ID_RENAME                       3
#define IDC_ARRIVAL_FUNCTIONS           4
#define ID_REMOVE                       4
#define IDC_DECLASS                     5
#define ID_SETCURRENT                   5
#define IDC_IMPORT                      6
#define ID_ADD                          7
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDB_LIGHTBULB                   102
#define IDC_PRINTBROWSER                109
#define ID_SRWND_HELP                   113
#define IDR_STAGERACE                   114
#define IDR_STAGERACESERVER             115
#define IDR_STAGERACECOMDOC             116
#define IDR_SRHALFSTAGE                 117
#define IDR_MAINFRAME                   128
#define IDR_STAGERACEDOC                129
#define IDD_COMPETITOR                  130
#define IDS_BONUS1                      130
#define IDB_OPTIONS_PANEL_IMAGES        130
#define IDS_BONUS2                      131
#define IDS_BONUS3                      132
#define IDS_BONUS4                      133
#define IDS_BONUS5                      134
#define IDS_BONUS6                      135
#define IDB_TOTAAL                      136
#define IDS_BONUS7                      136
#define IDS_BONUS8                      137
#define IDS_BONUS9                      138
#define IDS_BONUS10                     139
#define IDS_BONUS11                     140
#define IDS_BONUS12                     141
#define IDR_CONFIGURE                   142
#define IDS_BONUS13                     142
#define IDS_BONUS14                     143
#define IDB_TREE                        144
#define IDS_BONUS15                     144
#define IDD_COMMUNIQUE                  145
#define IDS_BONUS16                     145
#define IDS_BONUS17                     146
#define IDS_BONUS18                     147
#define IDS_BONUS19                     148
#define IDD_STARTSCREEN                 149
#define IDS_BONUS20                     149
#define IDS_BONUS21                     150
#define IDD_HALFSTAGETRIALDAT           151
#define IDS_BONUS22                     151
#define IDS_BONUS23                     152
#define IDS_BONUS24                     153
#define IDS_BONUS25                     154
#define IDS_SPRINT1                     155
#define IDS_SPRINT2                     156
#define IDS_SPRINT3                     157
#define IDS_SPRINT4                     158
#define IDC_STATIC1                     158
#define IDS_SPRINT5                     159
#define IDS_SPRINT6                     160
#define IDS_SPRINT7                     161
#define IDS_SPRINT8                     162
#define IDS_SPRINT9                     163
#define IDS_SPRINT10                    164
#define IDD_FULLSTAGETRIALDAT           165
#define IDS_SPRINT11                    165
#define IDD_LISTARRIVAL                 166
#define IDS_SPRINT12                    166
#define IDS_SPRINT13                    167
#define IDS_SPRINT14                    168
#define IDS_SPRINT15                    169
#define IDS_SPRINT16                    170
#define IDC_NEXTTIP                     170
#define IDR_ARRIVALFUNCTIONS            171
#define IDS_SPRINT17                    171
#define IDC_STARTUP                     171
#define IDS_SPRINT18                    172
#define IDC_TIPSTRING                   172
#define IDS_SPRINT19                    173
#define IDS_SPRINT20                    174
#define IDD_LISTTIMETRIALARRIVAL        175
#define IDS_SPRINT21                    175
#define IDS_SPRINT22                    176
#define IDS_SPRINT23                    177
#define IDD_LISTTIMETRIALORDER          178
#define IDS_SPRINT24                    178
#define IDS_SPRINT25                    179
#define IDS_CLIMB1                      180
#define IDS_CLIMB2                      181
#define IDR_TTORDERFUNCTIONS            182
#define IDS_CLIMB3                      182
#define IDS_CLIMB4                      183
#define IDS_CLIMB5                      184
#define IDS_CLIMB6                      185
#define IDS_CLIMB7                      186
#define IDS_CLIMB8                      187
#define IDS_CLIMB9                      188
#define IDS_CLIMB10                     189
#define IDS_CLIMB11                     190
#define IDS_CLIMB12                     191
#define IDD_LISTSIGNOUTS                192
#define IDS_CLIMB13                     192
#define IDS_CLIMB14                     193
#define IDS_CLIMB15                     194
#define IDS_CLIMB16                     195
#define IDS_CLIMB17                     196
#define IDS_CLIMB18                     197
#define IDS_CLIMB19                     198
#define IDD_TEAM                        199
#define IDS_CLIMB20                     199
#define IDS_CLIMB21                     200
#define IDS_CLIMB22                     201
#define IDS_CLIMB23                     202
#define IDS_CLIMB24                     203
#define IDS_CLIMB25                     204
#define IDD_TIPOFTHEDAY                 204
#define IDS_MBC_1                       205
#define IDS_MBT_1                       206
#define IDS_DIV25                       207
#define IDS_DIV82                       208
#define IDS_MBC_3                       209
#define IDS_MBT_3                       210
#define IDS_MBC_4                       211
#define IDS_MBT_4                       212
#define IDD_REPORT                      213
#define IDS_MBC_5                       213
#define IDS_MBT_5                       214
#define IDD_GETPWD                      215
#define IDS_MBC_6                       215
#define IDD_WAIT4CLASSIFICATION         216
#define IDS_MBT_6                       216
#define IDS_DIV1                        217
#define IDS_MBC_7                       218
#define IDS_MBC_7A                      218
#define IDS_MBT_7                       219
#define IDD_MOUNTAINDAT                 220
#define IDS_MBC_8                       220
#define IDD_SPRINTDAT                   221
#define IDS_MBT_8                       221
#define IDD_BONUSDAT                    222
#define IDS_MBC_9                       222
#define IDS_MBT_9                       223
#define IDS_DIV2                        224
#define IDS_DIV3                        225
#define IDD_CREDITS                     226
#define IDS_DIV4                        226
#define IDS_DIV5                        227
#define IDD_TTORDER_INTERVAL            228
#define IDS_DIV6                        228
#define IDS_DIV7                        229
#define IDS_DIV8                        230
#define IDS_DIV9                        231
#define IDR_ACTIVEDOCTRACKER            232
#define IDS_DIV10                       233
#define IDS_MBC_10                      234
#define IDS_MBT_10                      235
#define IDS_MBC_11                      236
#define IDS_MBT_11                      237
#define IDR_LICENSE                     238
#define IDS_DIV11                       238
#define IDS_DIV12                       239
#define IDS_DIV13                       240
#define IDS_DIV14                       241
#define IDS_DIV15                       242
#define IDS_DIV16                       243
#define IDS_MBC_12                      244
#define IDS_MBT_12                      245
#define IDS_MBC_13                      246
#define IDS_MBT_13                      247
#define IDS_MBC_14                      248
#define IDS_MBT_14                      249
#define IDS_MBC_15                      250
#define IDR_CREDITS                     250
#define IDS_MBT_15                      251
#define IDS_MBC_16                      252
#define IDD_OPTIONS                     252
#define IDS_MBT_16                      253
#define IDS_MBC_17                      254
#define IDS_MBT_17                      255
#define IDS_MBC_18                      256
#define IDS_MBT_18                      257
#define IDD_ARRIVALIMPORTPREVIEW        257
#define IDS_MBC_19                      258
#define IDS_MBT_19                      259
#define IDS_MBC_20                      260
#define IDS_MBT_20                      261
#define IDS_MBC_21                      262
#define IDS_MBT_21                      263
#define IDD_CHECKIMPORTFILE             263
#define IDS_DIV17                       264
#define IDS_DIV18                       265
#define IDS_DIV19                       266
#define IDB_TREESTATE                   266
#define IDS_DIV20                       267
#define IDS_MBC_22                      268
#define IDS_MBT_22                      269
#define IDS_MBC_23                      270
#define IDD_IDVIEW                      270
#define IDS_MBT_23                      271
#define IDS_MBC_24                      272
#define IDS_MBT_24                      273
#define IDS_MBC_25                      274
#define IDS_MBT_25                      275
#define IDD_MASKAPPLY                   275
#define IDS_MBC_26                      276
#define IDS_MBT_26                      277
#define IDD_TTORDEROPTIONS              277
#define IDS_DIV21                       278
#define IDD_MSGBOX_INDEXHTML            278
#define IDS_DIV22                       279
#define IDS_DIV23                       280
#define IDD_MSGBOX_HARDWAREKEY          280
#define IDS_DIV24                       281
#define IDS_MBC_51                      282
#define IDS_DIV26                       283
#define IDS_DIV27                       284
#define IDS_DIV28                       285
#define IDB_BANNERBOTTOM                285
#define IDS_MBC_27                      286
#define IDS_MBT_27                      287
#define IDS_MBC_28                      288
#define IDB_SPLASHLOGO_NL               288
#define IDS_MBT_28                      289
#define IDB_SPLASHLOGO_EN               289
#define IDS_MBC_29                      290
#define IDS_MBT_29                      291
#define IDS_DIV29                       292
#define IDI_DIALOG                      292
#define IDS_DIV30                       293
#define IDS_DIV31                       294
#define IDS_DIV32                       295
#define IDB_SPLASHLOGO                  295
#define IDS_MBC_30                      296
#define IDS_MBT_30                      297
#define IDB_MDICLIENT                   297
#define IDS_DIV33                       298
#define IDS_DIV34                       299
#define IDS_MBC_31                      300
#define IDD_FORMVIEWDETAILSEMPTY        300
#define IDS_MBT_31                      301
#define IDD_LISTCORRECTION              301
#define IDS_DIV35                       302
#define IDD_POINTSDAT                   302
#define IDS_DIV36                       303
#define IDD_MSGBOX_BEFOREPASTE          303
#define IDS_DIV37                       304
#define IDS_DIV38                       305
#define IDS_DIV39                       306
#define IDS_DIV40                       307
#define IDS_DIV41                       308
#define IDS_DIV42                       309
#define IDS_DIV43                       310
#define IDS_MBC_32                      311
#define IDI_KEY_LOCKED                  311
#define IDS_MBT_32                      312
#define IDI_KEY_FREE                    312
#define IDS_DIV44                       313
#define IDS_DIV45                       314
#define IDS_MBC_33                      315
#define IDR_ACTIVEDOCTRACKER_GRAY       315
#define IDS_MBT_33                      316
#define IDS_MBC_34                      317
#define IDB_CREDITS                     317
#define IDS_MBT_34                      318
#define IDS_MBC_35                      319
#define IDS_MBT_35                      320
#define IDS_MBC_36                      321
#define IDS_MBT_36                      322
#define IDS_DIV46                       323
#define IDS_MBC_37                      324
#define IDS_MBT_37                      325
#define IDS_MBC_38                      326
#define IDR_CONTEXTTREESTATE            326
#define IDS_MBT_38                      327
#define IDR_CONTEXTTREEITEMS            327
#define IDS_DIV47                       328
#define IDR_CONTEXTCOMPETITORS          328
#define IDS_DIV48                       329
#define IDR_CONTEXTTEAMS                329
#define IDS_DIV49                       330
#define IDR_CONTEXTPRESENTATION         330
#define IDS_MBC_39                      331
#define IDS_MBT_39                      332
#define IDD_DLGEVENTITEMSELECTION       332
#define IDS_DIV50                       333
#define IDD_SETT_RANK                   333
#define IDS_DIV51                       334
#define IDB_SETTINGS_TOPICS             334
#define IDD_SETT_PUBL                   334
#define IDS_MBC_40                      335
#define IDD_SETT_HTML                   335
#define IDS_MBT_40                      336
#define IDD_SETT_ACCESS                 336
#define IDS_MBC_41                      337
#define IDD_SETT_UPLOAD                 337
#define IDR_WAIT4CLASSIFICATION         337
#define IDS_MBT_41                      338
#define IDD_SETT_GENERAL                338
#define IDS_MBC_42                      339
#define IDD_TIPOFTHEDAY1                339
#define IDD_COMMUNIQUEPREVIEW           339
#define IDS_MBT_42                      340
#define IDD_DLGPROFILEPICKER            340
#define IDS_MBC_43                      341
#define IDB_BORDERLINE                  341
#define IDD_DLGPROFILENAME              341
#define IDS_MBT_43                      342
#define IDR_GENERATE                    342
#define IDD_DLGCOMPETITORSCLEANUP       342
#define IDS_DIV52                       343
#define IDD_ADDFILETOMONITOR            343
#define IDD_INSERTITEMINCOMMUNIQUE      343
#define IDS_MBC_46                      344
#define IDD_PARAGRAPHTITLE              344
#define IDS_MBT_46                      345
#define IDD_DLGAUTONUMBERCOMMUNIQUES    345
#define IDS_MBC_47                      346
#define IDD__TEST1                      346
#define IDS_MBT_47                      347
#define IDS_DIV53                       348
#define IDS_DIV54                       349
#define IDS_DIV55                       350
#define IDS_DIV56                       351
#define IDS_DIV57                       352
#define IDS_MBC_50                      353
#define IDR_SETMASK                     353
#define IDS_MBT_50                      354
#define IDR_COMMUNIQUE                  354
#define IDD_MOSTAGGRESSIVEDAT           354
#define IDS_DIV58                       355
#define IDD_ARRIVALINSERTPOSITIONS      355
#define IDS_DIV59                       356
#define IDS_DIV60                       357
#define IDS_DIV61                       358
#define IDS_DIV62                       359
#define IDS_DIV63                       360
#define IDS_DIV64                       361
#define IDS_DIV65                       362
#define IDS_DIV66                       363
#define IDS_MBC_7B                      364
#define IDS_MBC_53                      365
#define IDS_DIV83                       365
#define IDS_MBT_53                      366
#define IDS_MBT_51                      366
#define IDS_MBT_52                      367
#define IDS_MBC_52                      368
#define IDS_MBT_60                      369
#define IDS_MBC_60                      370
#define IDS_DIV113                      371
#define IDR_TREEVIEWMAIN                900
#define IDR_LISTVIEWCOMPETITORS         901
#define IDR_LISTVIEWTEAMS               902
#define IDR_PRESENTATIONVIEW            903
#define IDB_LISTSTATE                   904
#define IDS_DIV67                       904
#define IDS_DIV68                       905
#define IDB_TREECOMPETITORSTEAMS        905
#define IDB_COMPETITORSTEAMS            905
#define IDS_DIV69                       906
#define IDB_SPLASHLOGO_FR               906
#define IDS_DIV70                       907
#define IDS_DIV71                       908
#define IDS_DIV72                       909
#define IDS_DIV73                       910
#define IDS_DIV74                       911
#define IDS_DIV75                       912
#define CG_IDS_FILE_ABSENT              913
#define CG_IDS_FILE_CORRUPT             914
#define CG_IDS_DIDYOUKNOW               915
#define IDC_TIPFILE                     916
#define IDS_DIV76                       917
#define IDS_DIV77                       918
#define IDS_DIV78                       919
#define IDS_DIV79                       920
#define IDS_DIV91                       921
#define IDS_DIV92                       922
#define IDS_DIV93                       923
#define IDS_DIV94                       924
#define IDS_DIV95                       925
#define IDS_DIV96                       926
#define IDS_DIV97                       927
#define IDS_DIV98                       928
#define IDS_DIV99                       929
#define IDS_DIV100                      930
#define IDS_DIV101                      931
#define IDS_DIV102                      932
#define IDS_DIV103                      933
#define IDS_DIV104                      934
#define IDS_DIV106                      935
#define IDS_DIV107                      936
#define IDS_DIV108                      937
#define IDS_DIV109                      938
#define IDS_DIV110                      939
#define IDS_DIV111                      940
#define IDS_DIV112                      941
#define IDC_NAME                        1000
#define IDC_STANO                       1000
#define IDC_COMPETITOR                  1001
#define IDC_CONTENTS                    1002
#define IDC_COUNTRYCODE                 1004
#define IDC_UCICODE                     1005
#define IDC_LICENSE                     1009
#define IDC_STARTEMPTY                  1009
#define IDC_CATEGORY                    1010
#define IDC_ORGANISER                   1010
#define IDC_ADDONLY                     1010
#define IDC_EVENTNAME                   1011
#define IDC_DATES                       1012
#define IDC_ABOUT_NAME                  1013
#define IDC_ABOUT_VERSION               1014
#define IDC_ABOUT_HARDWAREKEY           1015
#define IDC_ABOUT_HARDWAREKEYCONTENTS   1016
#define IDC_MAINCATEGORY                1016
#define IDC_EVENTSUBTITLE               1019
#define IDC_LOCATION                    1020
#define IDC_ABOUT_DEMO                  1021
#define IDC_TITLE                       1021
#define IDC_OPENINGHOUR                 1022
#define IDC_DISTANCE                    1023
#define IDC_CLSPONSOR_MASK4             1024
#define IDC_TIMECUT                     1025
#define IDC_CLSPONSOR_MASK5             1025
#define IDC_DATE                        1026
#define IDC_CLSPONSOR_MASK6             1026
#define IDC_CLSPONSOR_MASK7             1027
#define IDC_CLSPONSOR_MASK8             1028
#define IDC_CLSPONSOR_MASK9             1029
#define IDC_CLSPONSOR_MASK10            1030
#define IDC_ARRIVAL_RANK                1033
#define IDC_ARRIVAL_STANO               1035
#define IDC_ARRIVAL_TIME                1036
#define IDC_SUBMIT                      1039
#define IDC_LISTCLIMB                   1043
#define IDC_ROUNDS                      1046
#define IDC_LIST_1234                   1048
#define IDC_BONUSSPRINTCOUNT            1050
#define IDC_ARRIVALIMPORTSPIN           1066
#define IDC_ARRIVALIMPORT_ROUND         1067
#define IDC_ARRIVALIMPORTSPIN2          1068
#define IDC_ARRIVALIMPORT_HEAT          1069
#define IDC_ARRIVALIMPORTSPIN3          1070
#define IDC_VERSION_NUMBER              1076
#define IDC_URL                         1077
#define IDC_PATHALGE                    1077
#define IDC_COPIES                      1077
#define IDC_PATHAMB                     1078
#define IDC_ARRIVALIMPORTRANKSTART      1079
#define IDC_PATHLYNX                    1079
#define IDC_ARRIVALIMPORTSTANOSTART     1080
#define IDC_ARRIVALIMPORTRANKEND        1081
#define IDC_ARRIVALIMPORTSTANOEND       1082
#define IDC_ARRIVALIMPORTTIMESTART      1083
#define IDC_ARRIVALIMPORTTIMEEND        1084
#define IDC_ARRIVALIMPORTRANKCOL        1085
#define IDC_ARRIVALIMPORTSTANOCOL       1086
#define IDC_ARRIVALIMPORTTIMECOL        1087
#define IDC_SETTINGS_BGCOLOR            1123
#define IDC_SETTINGS_TITLECOLOR         1124
#define IDC_SETTINGS_DESCRIPTCOLOR      1125
#define IDC_SETTINGS_EVENTLOGO          1126
#define IDC_SETTINGS_BODYCOLOR          1127
#define IDC_SETTINGS_USERNAME           1127
#define IDC_SETTINGS_PASSWORD           1128
#define IDC_SETTINGS_REMOTEDIR          1129
#define IDC_MATCH                       1130
#define IDC_SETTINGS_HOSTADDRESS        1131
#define IDC_BONUSSPRINT                 1131
#define IDC_BONUSFINISH                 1132
#define IDC_POINTSCLIMB2                1133
#define IDC_POINTSCLIMB4                1134
#define IDC_SETTINGS_SIGNATURE          1136
#define IDC_MANAGER                     1140
#define IDC_COUNTRY                     1141
#define IDC_TEAM                        1141
#define IDC_CODE                        1142
#define IDC_PROGRESS                    1149
#define IDC_ABOUT_TOTAALLOGO            1150
#define IDC_PASSWORD                    1157
#define IDC_KEYNO                       1158
#define IDC_EMAIL                       1164
#define IDC_WAIT4CLASSIFICATION         1165
#define IDC_WEBSITE                     1165
#define IDC_STAGERACELOGO               1166
#define IDC_PROGRESS4CLASSIFICATION     1167
#define IDC_LOADING_TEXT                1167
#define IDC_STAGERACELOGO2              1168
#define IDC_POINTSSPRINT                1171
#define IDC_POINTSFINISH                1172
#define IDC_POINTSSPRINTCOUNT           1173
#define IDC_POINTSCLIMB1                1174
#define IDC_POINTSCLIMB3                1175
#define IDC_ADD                         1176
#define IDC_REMOVE                      1177
#define IDC_ARRIVALIMPORTRANK           1177
#define IDC_SUPPRESS_HWKCHECK           1177
#define IDC_CHECKIMPORTFILEPROCEED      1177
#define IDC_FUTURESUPPRESS              1177
#define IDC_TIMETRIAL                   1178
#define IDC_IMPORTCHECKDIALOG           1178
#define IDC_AVOIDCONSECUTIVETEAMMEMBERS 1178
#define IDC_STANDARD                    1178
#define IDC_POINTSCLIMBHC               1178
#define IDC_EXCLUDE                     1179
#define IDC_LEAVEPLACESFORDROPPEDTEAMS  1179
#define IDC_ONEFORTEAMSCLASS            1180
#define IDC_INTERVAL                    1193
#define IDC_DONGLE                      1194
#define IDC_STARTTIME                   1194
#define IDC_HELP_ENGLISH                1197
#define IDC_HELP_DUTCH                  1198
#define IDC_ARRIVALIMPORTPREVIEW        1199
#define IDC_ARRIVALIMPORTHEADER         1202
#define IDC_SPIN1                       1203
#define IDC_SPIN2                       1204
#define IDC_SPIN3                       1205
#define IDC_SPIN4                       1206
#define IDC_SPIN5                       1207
#define IDC_ARRIVALIMPORTHEADERSIZE     1208
#define IDC_SPIN6                       1209
#define IDC_SPIN7                       1210
#define IDC_ARRIVALIMPORTTYPE           1211
#define IDC_ARRIVALIMPORTTYPE2          1211
#define IDC_ARRIVALIMPORTTYPE1          1212
#define IDC_ARRIVALIMPORTDECIMALS       1213
#define IDC_SPIN8                       1214
#define IDC_SPIN9                       1215
#define IDC_SPIN10                      1216
#define IDC_SPIN11                      1217
#define IDC_SETTINGS_MASK1ICON          1222
#define IDC_SETTINGS_MASK2ICON          1223
#define IDC_SETTINGS_MASK3ICON          1224
#define IDC_SETTINGS_CROSSOUTTEAMNAMESMODULUS 1225
#define IDC_ARRIVALIMPORTSEPARATION     1226
#define IDC_SETTINGS_SAMEGAP            1226
#define IDC_ARRIVALIMPORTSEPARATION1    1227
#define IDC_ARRIVALIMPORTTIMENOTATION   1228
#define IDC_ARRIVALIMPORTTIMENOTATION1  1229
#define IDC_ARRIVALIMPORTALGEOPTIC      1231
#define IDC_ARRIVALIMPORTAMBCHRONX      1232
#define IDC_ARRIVALIMPORTLYNXFINISHLYNX 1233
#define IDC_ARRIVALIMPORTSKUNKWARETTWARE 1234
#define IDC_ARRIVALIMPORTOMEGACL        1235
#define IDC_FILENAME                    1236
#define IDC_FILETIME                    1237
#define IDC_ARRIVALIMPORTSEPARATOR      1237
#define IDC_SYSTEMTIME                  1238
#define IDC_BROWSEOMEGA                 1238
#define IDC_BROWSEALGE                  1239
#define IDC_BROWSEAMB                   1240
#define IDC_PATHOMEGA                   1241
#define IDC_BROWSELYNX                  1242
#define IDC_IDSPIN                      1243
#define IDC_BROWSESKUNKWARE             1243
#define IDC_ID                          1244
#define IDC_COMNR                       1245
#define IDC_SETTINGS_STYLESHEET         1252
#define IDC_SETTINGS_FONTSIZE           1253
#define IDC_SETTINGS_COLUMNSPACING      1254
#define IDC_FIELD                       1257
#define IDC_VALUE                       1261
#define IDC_ARRIVALIMPORT_EVENT         1263
#define IDC_INSERTORDERTEAMVEHICLES_STAGE 1264
#define IDC_STATICDATE                  1265
#define IDC_FORMVIEWDETAILSEMPTYSIZE    1266
#define IDC_INSERTORDERTEAMVEHICLES_GENERAL 1267
#define IDC_NEWTEAM                     1269
#define IDS_INSERTORDERTEAMVEHICLES     1271
#define IDC_ARRIVAL_LISTAVAILABLE       1282
#define IDC_ARRIVAL_LISTARRIVAL         1283
#define IDC_ARRIVAL_COUNTAVAILABLE      1284
#define IDC_ARRIVAL_COUNTARRIVAL        1285
#define IDC_ARRIVAL_TITLEAVAILABLE      1286
#define IDC_ARRIVAL_TITLEARRIVAL        1287
#define IDC_ARRIVAL_BAR                 1288
#define IDC_ARRIVAL_LABELSTANO          1289
#define IDC_ARRIVAL_LABELTIME           1290
#define IDC_ARRIVAL_INFO                1291
#define IDC_ARRIVAL_LABELRANK           1292
#define IDC_ARRIVAL_ORDER               1295
#define IDC_CORRECTION_LISTCORRECTION   1296
#define IDC_CORRECTION_GROUPBOX         1297
#define IDC_CORRECTION_LABELSTANO       1298
#define IDC_CORRECTION_LABELBONUS       1299
#define IDC_CORRECTION_LABELPENALTY     1300
#define IDC_CORRECTION_PENALTY          1303
#define IDC_CORRECTION_BONUS            1304
#define IDC_CORRECTION_STANO            1305
#define IDC_SETTINGS_LANGUAGESSOURCE    1307
#define IDC_SETTINGS_REMOVEREQUIREDLANGUAGE 1308
#define IDC_SETTINGS_REQUIREDLANGUAGES  1309
#define IDC_SETTINGS_ADDREQUIREDLANGUAGE 1310
#define IDC_PRINT                       1314
#define IDC_SETTINGS_BINARYSETTINGS     1314
#define IDC_CLEAR                       1315
#define IDC_UPLOAD                      1316
#define IDC_MAIL                        1317
#define IDC_COPYTO                      1318
#define IDC_SIGNOUTS_LISTSIGNOUTS       1320
#define IDC_SIGNOUTS_LABELSTANO         1321
#define IDC_SIGNOUTS_STANO              1322
#define IDC_SIGNOUTS_LABELREASON        1323
#define IDC_SIGNOUTS_ADD                1324
#define IDC_SIGNOUTS_DELETE             1325
#define IDC_SIGNOUTS_REASON             1326
#define IDC_POINTS                      1328
#define IDC_STANO_ACTIVE                1329
#define IDC_STANO_NONACTIVE             1330
#define IDC_PASTE_WITHOUTTEAMINPUT      1330
#define IDC_STATIC_TOTALCOPIES          1333
#define IDC_STATIC_COPIES               1334
#define IDC_TOTALCOPIES                 1335
#define IDC_SPINNER_TOTALCOPIES         1336
#define IDC_SPINNER_COPIES              1337
#define IDC_EVENTITEMS                  1339
#define IDC_SETTINGSRANKING_BUNCHSIZE   1340
#define IDC_SETTINGSRANKING_DEPTHSTAGE  1341
#define IDC_SETTINGSRANKING_DEPTHINTERMEDIATE 1342
#define IDC_OPTIONS_PRINTBACKGROUND     1344
#define IDC_BROWSER                     1345
#define IDC_OPTIONS_INDICATEMISSINGLANGUAGESTRINGS 1345
#define IDC_PREVIEW                     1346
#define IDC_OPTIONS_USECONTROLFORCOMPETITORPASTE 1347
#define IDC_TIMETRIAL_GROSSTIMES        1348
#define IDC_OPTIONS_HIDEFUNCTIONSFORSPRINTS 1348
#define IDC_TIMETRIAL_NETTIMES          1349
#define IDC_OPTIONS_PROTECTDIALOGSFROMESCAPE 1349
#define IDC_OPTIONS_USEINSDELFORARRIVALS 1350
#define IDC_OPTIONS_SUPPRESSHWKCHECK    1353
#define IDC_OPTIONS_IMPORTCHECKDIALOG   1354
#define IDC_OPTIONS_HELP_ENGLISH        1355
#define IDC_OPTIONS_HELP_DUTCH          1356
#define IDC_OPTIONS_PATH_OMEGA          1357
#define IDC_OPTIONS_PATH_ALGE           1358
#define IDC_OPTIONS_PATH_AMB            1359
#define IDC_OPTIONS_PATH_LYNX           1360
#define IDC_OPTIONS_PATH_SKUNKWARE      1361
#define IDC_OPTIONS_PATH_WORK           1362
#define IDC_BROWSEWORK                  1363
#define IDC_OPTIONS_PATH_EDITOR         1364
#define IDC_INDIVIDUAL                  1364
#define IDC_BROWSEEDITOR                1365
#define IDC_TEAMS                       1365
#define IDC_USEORDER                    1368
#define IDC_HELP_OK                     1370
#define IDC_LIST1                       1371
#define IDC_LIST                        1371
#define IDC_ARRIVAL_ANTICIPATEDTIME     1374
#define IDC_ARRIVAL_ANTICIPATETIME      1375
#define IDC_SETTINGS_CUSTOMHTML_TOP     1379
#define IDC_SETTINGS_CUSTOMHTML_BOTTOM  1380
#define IDC_ARRIVAL_TIMECUT             1381
#define IDC_ARRIVAL_LABELTIMECUT1       1382
#define IDC_ARRIVAL_LABELTIMECUT2       1383
#define IDC_INDICATOR_GENERAL           1385
#define IDC_INDICATOR_RANKING           1386
#define IDC_ADJUSTFILENAMES             1386
#define IDC_INDICATOR_PUBLICATION       1387
#define IDC_USEPROFILENAMES             1387
#define IDC_REMOVEREPEATEDSPACES        1387
#define IDC_INDICATOR_HTML              1388
#define IDC_REMOVESPACESAROUND          1388
#define IDC_INDICATOR_UPLOAD            1389
#define IDC_COPYUCITOCOUNTRY            1389
#define IDC_INDICATOR_ACCESS            1390
#define IDC_CAPITALIZEBEFORECOMMA       1392
#define IDC_CLEANUPCOMMAS               1393
#define IDC_BROWSE                      1394
#define IDC_RADIO1                      1395
#define IDC_RADIO2                      1396
#define IDC_RADIO3                      1397
#define IDC_IDENTIFIER                  1398
#define IDC_SETTINGS_FONTSIZE_STATIC    1399
#define IDC_AUTONUMBER_CROSSOUTLISTS    1400
#define IDC_AUTONUMBER_SIGNINLISTS      1401
#define IDC_AUTONUMBER_PUBLISHALL       1402
#define IDC_LIST_HC1234                 1402
#define IDC_AUTONUMBER_STANOSORTEDGENERAL 1402
#define IDC_SETTINGS_COLUMNSPACING_STATIC 1404
#define IDC_CLSPONSOR_GENERAL           1405
#define IDC_CLSPONSOR_TEAMS             1406
#define IDC_CLSPONSOR_SPRINT            1407
#define IDC_CLSPONSOR_POINTS            1408
#define IDC_CLSPONSOR_CLIMB             1409
#define IDC_CLSPONSOR_MOSTAGGRESSIVE    1410
#define IDC_CLSPONSOR_MASK1             1411
#define IDC_CLSPONSOR_MASK2             1412
#define IDC_CLSPONSOR_MASK3             1413
#define IDC_STATIC15                    1427
#define IDC_SETTINGS_EVENTLOGO_BUTTON   1435
#define IDC_SETTINGS_STYLESHEET_BUTTON  1436
#define IDC_COUNT                       1437
#define IDC_SPIN                        1438
#define IDC_MASK1                       1439
#define IDC_MASK2                       1440
#define IDC_MASK3                       1441
#define IDC_MASK4                       1442
#define IDC_MASK5                       1443
#define IDC_MASK6                       1444
#define IDC_MASK7                       1445
#define IDC_MASK8                       1446
#define IDC_MASK9                       1447
#define IDC_MASK10                      1448
#define IDC_TIMETRIALSTARTLATECHANGE    1449
#define IDC_CREDITS                     2000
#define IDS_SETT_ACCESS                 25000
#define IDS_SETT_ACCESS_FREE            25001
#define IDS_SETT_ACCESS_KEY             25002
#define IDS_SETT_ACCESS_PASSWORD        25003
#define IDS_SETT_GNRL_INPUTACCURACY     25004
#define IDS_SETT_GNRL_INPUTACCURACY_100 25005
#define IDS_SETT_GNRL_INPUTACCURACY_1000 25006
#define IDS_SETT_GNRL_MASKS             25007
#define IDS_SETT_GNRL_MASKS_USE1        25008
#define IDS_SETT_GNRL_MASKS_USE2        25009
#define IDS_SETT_GNRL_MASKS_USE3        25010
#define IDS_SETT_HTML_TOC               25011
#define IDS_SETT_HTML_TOC_EVENTNAME     25012
#define IDS_SETT_HTML_TOC_INDEXHTML     25013
#define IDS_SETT_PUBL_COLS              25014
#define IDS_SETT_PUBL_COLS_INDIVIDUAL   25015
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_CATEGORY 25016
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_COUNTRY 25017
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_GENERAL 25018
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_GENERAL_GAP 25019
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_GENERAL_NEWGAP 25020
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_GENERAL_TIME 25021
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_LICENSE 25022
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_RANK 25023
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_RIDER 25024
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE 25025
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE_BONUSES 25026
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE_GAP 25027
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE_NEWGAP 25028
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE_PENALTY 25029
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE_TIME 25030
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STAGE_TIMEONLYDRAWTHOUSANDTHS 25031
#define IDS_SETT_GNRL_PROLOGUE          25031
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_STANO 25032
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_TEAMCODE 25033
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_TEAMCODEWITHOUTCOLUMNTITLE 25034
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_TEAMNAME 25035
#define IDS_SETT_PUBL_COLS_INDIVIDUAL_UCICODE 25036
#define IDS_SETT_PUBL_COLS_LISTCOMP1    25037
#define IDS_SETT_PUBL_COLS_LISTCOMP1_CATEGORY 25038
#define IDS_SETT_PUBL_COLS_LISTCOMP1_COUNTRY 25039
#define IDS_SETT_PUBL_COLS_LISTCOMP1_LICENSE 25040
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK1 25041
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK2 25042
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK3 25043
#define IDS_SETT_PUBL_COLS_LISTCOMP1_RIDER 25044
#define IDS_SETT_PUBL_COLS_LISTCOMP1_STANO 25045
#define IDS_SETT_PUBL_COLS_LISTCOMP1_TEAMCODE 25046
#define IDS_SETT_PUBL_COLS_LISTCOMP1_TEAMCODEWITHOUTCOLUMNTITLE 25047
#define IDS_SETT_PUBL_COLS_LISTCOMP1_TEAMNAME 25048
#define IDS_SETT_PUBL_COLS_LISTCOMP1_UCICODE 25049
#define IDS_SETT_PUBL_COLS_LISTCOMP2    25050
#define IDS_SETT_PUBL_COLS_LISTCOMP2_CATEGORY 25051
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COUNTRY 25052
#define IDS_SETT_PUBL_COLS_LISTCOMP2_LICENSE 25053
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK1 25054
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK2 25055
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK3 25056
#define IDS_SETT_PUBL_COLS_LISTCOMP2_RIDER 25057
#define IDS_SETT_PUBL_COLS_LISTCOMP2_STANO 25058
#define IDS_SETT_PUBL_COLS_LISTCOMP2_UCICODE 25059
#define IDS_SETT_PUBL_COLS_TEAM         25060
#define IDS_SETT_PUBL_COLS_TEAM_GAP     25061
#define IDS_SETT_PUBL_COLS_TEAM_INVOLVEDBUNCH 25062
#define IDS_SETT_PUBL_COLS_TEAM_NEWGAP  25063
#define IDS_SETT_PUBL_COLS_TEAM_RANK    25064
#define IDS_SETT_PUBL_COLS_TEAM_TEAMCODE 25065
#define IDS_SETT_PUBL_COLS_TEAM_TEAMCODEWITHOUTCOLUMNTITLE 25066
#define IDS_SETT_PUBL_COLS_TEAM_TEAMNAME 25067
#define IDS_SETT_PUBL_COLS_TEAM_TIME    25068
#define IDS_SETT_PUBL_COMMNOS           25069
#define IDS_SETT_PUBL_COMMNOS_USE       25070
#define IDS_SETT_PUBL_CROSSOUTLISTS     25071
#define IDS_SETT_PUBL_CROSSOUTLISTS_PRINTTEAMNAMES 25072
#define IDS_SETT_PUBL_LOGOPOSITION      25073
#define IDS_SETT_PUBL_HEADER_LOGOPOSITION 25073
#define IDS_SETT_PUBL_LOGOPOSITION_CENTER 25074
#define IDS_SETT_PUBL_HEADER_LOGOPOSITION_CENTER 25074
#define IDS_SETT_PUBL_LOGOPOSITION_LEFT 25075
#define IDS_SETT_PUBL_HEADER_LOGOPOSITION_LEFT 25075
#define IDS_SETT_PUBL_LOGOPOSITION_RIGHT 25076
#define IDS_SETT_PUBL_HEADER_LOGOPOSITION_RIGHT 25076
#define IDS_SETT_PUBL_MASKSONCOMPLIST   25077
#define IDS_SETT_PUBL_MASKSONCOMPLIST_1 25078
#define IDS_SETT_PUBL_MASKSONCOMPLIST_2 25079
#define IDS_SETT_PUBL_MASKSONCOMPLIST_3 25080
#define IDS_SETT_PUBL_HEADER_TITLE      25081
#define IDS_SETT_PUBL_HEADER_TITLEALIGN 25082
#define IDS_SETT_GNRL_PROLOGUE_EXISTS   25082
#define IDS_SETT_PUBL_HEADER_TITLEALIGN_CENTER 25083
#define IDS_SETT_PUBL_HEADER_TITLEALIGN_DEFAULT 25084
#define IDS_SETT_PUBL_HEADER_TITLEALIGN_RIGHT 25085
#define IDS_SETT_PUBL_HEADER_TITLE_DONTSHOW 25086
#define IDS_SETT_HTML_STYLE             25087
#define IDS_SETT_HTML_STYLE_EXTERNAL    25088
#define IDS_SETT_HTML_STYLE_INTERNAL    25089
#define IDS_DIV80                       25090
#define IDS_SETT_PUBL_TT                25091
#define IDS_SETT_PUBL_TT_SHOWACCURATE   25092
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN  25093
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE 25094
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_TIMESTAMP 25095
#define IDS_SETT_RANK_CLIMB             25096
#define IDS_SETT_RANK_CLIMB_ONLATESTRANKING 25097
#define IDS_SETT_RANK_CLIMB_ONMOSTHIGHRANKINGS 25098
#define IDS_SETT_RANK_GENERAL           25099
#define IDS_SETT_RANK_GENERAL_SORT_ONLATESTRANKING 25100
#define IDS_SETT_RANK_GENERAL_SORT_ONSUMRANKINGS 25101
#define IDS_SETT_RANK_GENERAL_SORT_ONTIMETRIALS 25102
#define IDS_SETT_RANK_INDIVIDUAL        25103
#define IDS_SETT_RANK_POINTS            25104
#define IDS_SETT_RANK_POINTS_ONLATESTRANKING 25105
#define IDS_SETT_RANK_POINTS_ONMOSTHIGHRANKINGS 25106
#define IDS_SETT_RANK_SPRINT            25107
#define IDS_SETT_RANK_SPRINT_INCLUDEFINISH 25108
#define IDS_SETT_RANK_SPRINT_ONLATESTRANKING 25109
#define IDS_SETT_RANK_SPRINT_ONMOSTHIGHRANKINGS 25110
#define IDS_SETT_RANK_TEAMS             25111
#define IDS_SETT_RANK_TEAMS_DECIDING    25112
#define IDS_SETT_RANK_TEAMS_DECIDING_FIRST 25113
#define IDS_SETT_RANK_TEAMS_DECIDING_LAST 25114
#define IDS_SETT_RANK_TEAMS_GENERAL     25115
#define IDS_SETT_RANK_TEAMS_GENERAL_ONWITHOUTSUMRANKINGS 25116
#define IDS_SETT_RANK_TEAMS_GENERAL_ONWITHSUMRANKINGS 25117
#define IDS_SETT_RANK_TEAMS_GENERATE    25118
#define IDS_SETT_RANK_TEAMS_STAGE       25119
#define IDS_SETT_RANK_TEAMS_STAGE_ONWITHOUTSUMRANKINGS 25120
#define IDS_SETT_RANK_TEAMS_STAGE_ONWITHSUMRANKINGS 25121
#define IDS_SETT_UPLOAD                 25122
#define IDS_SETT_UPLOAD_ALLOW           25123
#define IDS_SETT_PUBL_DOCRECOGNITION_USE 25124
#define IDS_SETT_PUBL_HEADER_DOCRECOGNITION_USE 25124
#define IDS_SETT_PUBL_FOOTER            25125
#define IDS_SETT_PUBL_FOOTER_DROPOUTS   25126
#define IDS_SETT_PUBL_FOOTER_STATS      25127
#define IDS_SETT_PUBL_FOOTER_STATS_DROPOUTS 25128
#define IDS_SETT_PUBL_FOOTER_STATS_OTHERS 25129
#define IDS_SETT_PUBL_HEADER            25130
#define IDS_SETT_PUBL_HEADER_PROPS      25131
#define IDS_SETT_PUBL_HEADER_PROPS_ORGANISER 25132
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL 25133
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_FULLSTAGE 25134
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_HALFSTAGE 25135
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_CATEGORY 25136
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_SPEED 25137
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_DISTANCE 25138
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_STAGE 25139
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_STAGE_OPENINGHOUR 25140
#define IDS_SETT_PUBL_HEADER_PROPS_TTORDER 25141
#define IDS_SETT_PUBL_HEADER_PROPS_TTORDER_FULLSTAGE 25142
#define IDS_SETT_PUBL_HEADER_PROPS_TTORDER_HALFSTAGE 25143
#define IDS_SETT_PUBL_HEADER_PROPS_TTORDER_CATEGORY 25144
#define IDS_SETT_PUBL_HEADER_PROPS_TTORDER_DISTANCE 25145
#define IDS_SETT_PUBL_HEADER_PROPS_TTORDER_OPENINGHOUR 25146
#define IDS_SETT_PUBL_HEADER_PROPS_CROSSOUT 25147
#define IDS_SETT_PUBL_HEADER_PROPS_CROSSOUT_FULLSTAGE 25148
#define IDS_SETT_PUBL_HEADER_PROPS_CROSSOUT_HALFSTAGE 25149
#define IDS_SETT_PUBL_HEADER_PROPS_CROSSOUT_CATEGORY 25150
#define IDS_SETT_PUBL_HEADER_PROPS_CROSSOUT_DISTANCE 25151
#define IDS_SETT_PUBL_HEADER_PROPS_CROSSOUT_OPENINGHOUR 25152
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS 25153
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS_ORGANISER 25154
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS_MAINLOCATION 25155
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS_DATES 25156
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS_CATEGORY 25157
#define IDS_SETT_PUBL_HEADER_PROPS_INDIVIDUAL_BESTTIME 25158
#define IDS_SETT_PUBL_FOOTER_SIGNOUTS   25159
#define IDS_SETT_PUBL_FOOTER_SIGNOUTS_ONSTAGES 25160
#define IDS_SETT_PUBL_COLS_TEAM_INVOLVEDBUNCH_INLINE 25160
#define IDS_SETT_PUBL_FOOTER_SIGNOUTS_ONCOMMUNIQUES 25161
#define IDS_SETT_PUBL_COLS_TEAM_INVOLVEDBUNCH_ASROWS 25161
#define IDS_SETT_PUBL_COLS_TEAM_INVOLVEDBUNCH_STANO 25162
#define IDS_DIV81                       25163
#define IDD_SETT_RANK_LASTRESORT        25164
#define IDD_SETT_RANK_LASTRESORT_STAGE_CL 25165
#define IDD_SETT_RANK_LASTRESORT_GENERAL_CL 25166
#define IDS_SETT_RANK_CLIMB_DIFFCATEGORIES 25167
#define IDS_SETT_PUBL_HEADER_DOCRECOGNITION_REPEAT 25168
#define IDS_SETT_PUBL_HEADER_PROPS_SIGNIN 25169
#define IDS_SETT_PUBL_HEADER_PROPS_SIGNIN_FULLSTAGE 25170
#define IDS_SETT_PUBL_HEADER_PROPS_SIGNIN_HALFSTAGE 25171
#define IDS_SETT_PUBL_HEADER_PROPS_SIGNIN_CATEGORY 25172
#define IDS_SETT_PUBL_HEADER_PROPS_SIGNIN_DISTANCE 25173
#define IDS_SETT_PUBL_HEADER_PROPS_SIGNIN_OPENINGHOUR 25174
#define IDS_SETT_PUBL_DISTANCES         25175
#define IDS_SETT_PUBL_DISTANCES_KM      25176
#define IDS_SETT_PUBL_DISTANCES_MILE    25177
#define IDS_SETT_GNRL_STAGENUMBERING    25178
#define IDS_SETT_HTML_CHARSET           25178
#define IDS_SETT_GNRL_STAGENUMBERING_SUPPRESS 25179
#define IDS_SETT_HTML_CHARSET_ISO1      25179
#define IDS_SETT_PUBL_FOOTER_ADVERTISEMENT 25180
#define IDS_SETT_HTML_CHARSET_ISO2      25180
#define IDS_SETT_PUBL_FOOTER_ADVERTISEMENT_LONG 25181
#define IDS_SETT_HTML_CHARSET_ISO3      25181
#define IDS_SETT_PUBL_FOOTER_ADVERTISEMENT_SHORT 25182
#define IDS_SETT_HTML_CHARSET_ISO4      25182
#define IDS_SETT_HTML_FONT              25183
#define IDS_SETT_HTML_CHARSET_ISO5      25183
#define IDS_SETT_HTML_FONT_TIMES        25184
#define IDS_SETT_HTML_CHARSET_ISO6      25184
#define IDS_SETT_HTML_FONT_ARIAL        25185
#define IDS_SETT_HTML_CHARSET_ISO7      25185
#define IDS_DIV84                       25186
#define IDS_SETT_HTML_CHARSET_ISO8      25186
#define IDS_DIV85                       25187
#define IDS_SETT_HTML_CHARSET_ISO9      25187
#define IDS_DIV86                       25188
#define IDS_SETT_HTML_CHARSET_ISO10     25188
#define IDS_DIV87                       25189
#define IDS_SETT_HTML_CHARSET_ISO11     25189
#define IDS_DIV88                       25190
#define IDS_DIV89                       25191
#define IDS_SETT_HTML_CHARSET_ISO13     25191
#define IDS_SETT_PUBL_FOOTER_CUTOFFS    25192
#define IDS_SETT_HTML_CHARSET_ISO14     25192
#define IDS_SETT_PUBL_FOOTER_STATS_CUTOFFS 25193
#define IDS_SETT_HTML_CHARSET_ISO15     25193
#define IDS_SETT_PUBL_HEADER_PROPS_DIRECTION 25194
#define IDS_SETT_HTML_CHARSET_ISO16     25194
#define IDS_SETT_PUBL_HEADER_PROPS_DIRECTION_VERTICAL 25195
#define IDS_SETT_HTML_CHARSET_WIN1250   25195
#define IDS_SETT_PUBL_HEADER_PROPS_DIRECTION_HORIZONTAL 25196
#define IDS_SETT_HTML_CHARSET_WIN1251   25196
#define IDS_SETT_HTML_FONTSIZE          25197
#define IDS_SETT_HTML_CHARSET_WIN1252   25197
#define IDS_SETT_HTML_FONTSIZE_PROC     25198
#define IDS_SETT_HTML_CHARSET_WIN1253   25198
#define IDS_SETT_HTML_FONTSIZE_ABS      25199
#define IDS_SETT_HTML_CHARSET_WIN1254   25199
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_TIMESTAMP_TIMEZONE 25200
#define IDS_SETT_HTML_CHARSET_WIN1255   25200
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE_OWN 25201
#define IDS_SETT_HTML_CHARSET_WIN1256   25201
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_TIMESTAMP_SECONDS 25202
#define IDS_SETT_HTML_CHARSET_WIN1257   25202
#define IDS_SETT_PUBL_TOC               25203
#define IDS_SETT_HTML_CHARSET_WIN1258   25203
#define IDS_SETT_PUBL_TOC_ORDER         25204
#define IDS_SETT_HTML_CHARSET_WIN874    25204
#define IDS_SETT_PUBL_TOC_ORDER_NORMAL  25205
#define IDS_SETT_PUBL_TOC_ORDER_REVERSE 25206
#define IDS_SETT_PUBL_TOC_COMPETITORS   25207
#define IDS_SETT_PUBL_TOC_COMPETITORS_TOP 25208
#define IDS_SETT_PUBL_TOC_COMPETITORS_BOTTOM 25209
#define IDS_SETT_PUBL_TT_SPEED          25210
#define IDS_SETT_HTML_PRINTDUMMY        25211
#define IDS_SETT_HTML_DUMMY             25211
#define IDS_SETT_HTML_DUMMY_PRINT       25212
#define IDS_SETT_HTML_HYPERLINKS        25213
#define IDS_SETT_HTML_HYPERLINKS_USE    25214
#define IDS_SETT_RANK_MOSTAGGRESSIVE    25215
#define IDS_DIV105                      25215
#define IDS_SETT_RANK_MOSTAGGRESSIVE_GENERATE 25216
#define IDS_SETT_PUBL_TT_SHOWACCURATEWITHDRAWS 25216
#define IDS_SETT_PUBL_TT_SHOWNORMAL     25217
#define IDS_SETT_PUBL_HEADER_SPONSOR    25218
#define IDS_SETT_PUBL_HEADER_SPONSOR_ASSUBTITLE 25219
#define IDS_SETT_PUBL_HEADER_SPONSOR_DONTUSE 25220
#define IDS_SETT_PUBL_HEADER_SPONSOR_ADDTOSUBTITLE 25221
#define IDS_SETT_PUBL_COLS_TEAM_INVOLVEDBUNCH_ASFULLROWS 25222
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS 25223
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS_1 25224
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS_2 25225
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS_3 25226
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS_4 25227
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS_5 25228
#define IDS_SETT_PUBL_COLS_LISTCOMP2_COLUMNS_6 25229
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE_URL 25230
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE_URL_ASWEB 25231
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE_URL_ASWEBWITHHTTP 25232
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE_URL_ASEMAIL 25233
#define IDS_SETT_PUBL_FOOTER_UNDERSIGN_SIGNATURE_URL_PLAIN 25234
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS_TEAMCOUNT 25235
#define IDS_SETT_PUBL_HEADER_PROPS_COMPETITORS_COMPCOUNT 25236
#define IDS_SETT_GNRL_MASKS_SUPPRESSMASKNO 25237
#define IDS_SETT_HTML_UNICODE           25238
#define IDS_SETT_HTML_UNICODE_PRINTUNICODE 25239
#define IDS_SETT_HTML_UNICODE_ENCODEUNICODE 25240
#define IDS_SETT_UPLOAD_ADDFOLDER       25241
#define IDS_SETT_GNRL_MASKS_USE4        25242
#define IDS_SETT_GNRL_MASKS_USE5        25243
#define IDS_SETT_GNRL_MASKS_USE6        25244
#define IDS_SETT_GNRL_MASKS_USE7        25245
#define IDS_SETT_GNRL_MASKS_USE8        25246
#define IDS_SETT_GNRL_MASKS_USE9        25247
#define IDS_SETT_GNRL_MASKS_USE10       25248
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK4 25249
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK5 25250
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK6 25251
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK7 25252
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK8 25253
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK9 25254
#define IDS_SETT_PUBL_COLS_LISTCOMP1_MASK10 25255
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK4 25256
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK5 25257
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK6 25258
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK7 25259
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK8 25260
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK9 25261
#define IDS_SETT_PUBL_COLS_LISTCOMP2_MASK10 25262
#define IDS_SETT_RANK_GENERAL_GENERATETSTANOSORTEDGENERAL 25263
#define IDS_SETT_PUBL_CROSSOUTLISTS_PRINTCOMPETITORNAMES 25264
#define IDS_SETT_RANK_SPRINT_PRINTSTAGE 25265
#define IDS_SETT_HTML_UCIFIXEDWIDTH     25266
#define IDS_SETT_HTML_CUSTOMONEACHPAGE  25267
#define IDS_SETT_HTML_CUSTOMONEACHPAGE_TOP 25268
#define IDS_SETT_HTML_CUSTOMONEACHPAGE_BOTTOM 25269
#define IDS_MBC_44                      32774
#define IDS_MBT_44                      32775
#define IDS_MBC_45                      32776
#define IDS_MBT_45                      32777
#define IDS_MBC_48                      32778
#define IDS_MBT_48                      32779
#define ID_VIEW_TLBAR_STANDARD          32791
#define IDS_MBC_49                      32792
#define IDS_MBT_49                      32793
#define IDS_MBC_54                      32794
#define IDS_MBT_54                      32795
#define IDS_MBC_55                      32796
#define IDS_MBT_55                      32797
#define IDS_MBC_56                      32798
#define IDS_MBT_56                      32799
#define IDS_MBC_57                      32800
#define IDS_MBT_57                      32801
#define ID_VIEW_MAINTRIALDAT            32802
#define IDS_MBC_58                      32802
#define IDS_MBT_58                      32803
#define IDS_MBC_59                      32804
#define IDS_MBT_59                      32805
#define ID_VIEW_TLBAR_CONFIGURE         32806
#define ID_EDIT_COMPETITORS             32807
#define ID_INSERT_COMMUNIQUE            32808
#define ID_CONFIGURE_CONFIGURE          32809
#define ID_CONFIGURE_DELETE             32810
#define IDS_MBC_61                      32811
#define IDS_MBT_61                      32812
#define ID_EDIT_EDITSELECTION           32813
#define IDS_MBC_62                      32814
#define IDS_MBT_62                      32815
#define ID_ARRIVAL_CHECK                32816
#define IDS_MBC_63                      32816
#define IDS_MBT_63                      32817
#define ID_ARRIVAL_GROUPT_1             32818
#define ID_ARRIVAL_GROUPT_2             32819
#define ID_ARRIVAL_GROUPT_3             32820
#define ID_ARRIVALFUNCTIONS_IMPORT      32821
#define ID_ARRIVAL_IMPORT               32822
#define ID_ARRIVAL_EMPTY                32824
#define ID_ARRIVAL_FUNCTIONS_CHECK      32825
#define ID_ARRIVAL_FUNCTIONS_GROUPT_1   32826
#define ID_ARRIVAL_FUNCTIONS_GROUPT_2   32827
#define ID_ARRIVAL_FUNCTIONS_GROUPT_3   32828
#define ID_ARRIVAL_FUNCTIONS_IMPORT     32829
#define ID_CONFIGURE_SETTINGS           32831
#define ID_INSERT_SIGNOUTS              32835
#define ID_PRESENTATION_GENERAL         32839
#define ID_PRESENTATION_STAGE           32841
#define ID_FILE_UPLOAD                  32842
#define ID_EDIT_TEAMS                   32843
#define ID_TIMETRIALORDERFUNCTIONS_REMOVEGAPS 32856
#define ID_TIMETRIALORDERFUNCTIONS_GAPS 32857
#define ID_PRESENTATION_MASK1           32863
#define ID_PRESENTATION_MASK3           32865
#define ID_PRESENTATION_MASK2           32868
#define ID_PRESENTATION_REFRESH         32871
#define ID_VIEW_REFRESH                 32872
#define ID_TIMETRIALORDERFUNCTIONS_AUTO 32873
#define ID_PRESENTATION_TEAM            32874
#define ID_TOOLS_TIMECALCULATOR         32879
#define ID_TOOLS_SPEEDCALCULATOR        32880
#define ID_TOOLS_OPTIONS                32881
#define ID_BEWERKEN_DOORHAALLIJSTENBIJWERKEN 32887
#define ID_EDIT_CROSSOUT                32888
#define ID_ARRIVAL_FUNCTIONS_REMOVEGAPS 32890
#define ID_ARRIVAL_FUNCTIONS_REMOVE1XSECONDS 32891
#define ID_TOOLS_EXPORTOPTIC            32892
#define ID_TOOLS_EXPORTCHRONX           32893
#define ID_TOOLS_EXPORTSCANOVISION      32894
#define ID_EDIT_PUBLISH                 32899
#define ID_TOOLS_GENERATETOC            32902
#define ID_TOOLS_EXPORTFINISHLYNX       32906
#define ID_TIMETRIALORDERFUNCTIONS_FROMLASTHALFSTAGE 32913
#define ID_TIMETRIALORDERFUNCTIONS_FROMLASTFULLSTAGE 32914
#define ID_HELP_SEARCH                  32917
#define ID_HELP_CONTENTS                32918
#define ID_HELP_LICENSE                 32919
#define ID_EDIT_DELETE                  32927
#define ID_INSERT_REPEATEDLY            32929
#define ID_EDIT_APPLYMASK               32942
#define ID_CONFIGURE_INSERT_FULLSTAGE   32943
#define ID_CONFIGURE_INSERT_HALFSTAGE   32944
#define ID_VIEW_TLBAR_TREEVIEWMAIN      32945
#define ID_VIEW_TREEVIEWMAIN            32951
#define ID_VIEW_LISTVIEWACTIVEDOC       32965
#define ID_VIEW_INFO                    32970
#define ID_EDIT_SELECT                  32975
#define ID_INSERT_COMPETITORTEAM        32976
#define ID_EDIT_PASTE_WITHSTANOS        32978
#define ID_EDIT_SWAPCOMPETITORS         32979
#define IDS_DIV90                       32980
#define IDS_DIV114                      32981
#define ID_VIEW_EVENTITEMSELECTION      32987
#define ID_EDIT_COPYTOSELECTIONDLG      32988
#define ID_EDIT_PUBLISH_PLUS            32991
#define ID_EDIT_PUBLISH_MINUS           32992
#define ID_HELP_TIPOFTHEDAY             32993
#define ID_FILE_PRINT_PREVIEW_2COLUMN   32996
#define ID_GENERATE_SELECTION           32997
#define ID_GENERATE_AUTOMATICALLY       33000
#define ID_GENERATE_ALL                 33001
#define ID_GENERATE_COMMUNIQUES         33002
#define ID_GENERATE_CROSSOUT            33003
#define ID_GENERATE_TOC                 33004
#define ID_GENERATE_ALLSTAGES           33005
#define ID_GENERATE_COMPETITORS         33006
#define ID_VIEW_TLBAR_GENERATE          33014
#define ID_TOOLS_EDITPUBL               33018
#define ID_GENERATE_READONLY            33019
#define ID_EDIT_SELECTALL               33020
#define ID_VIEW_EXPAND                  33021
#define ID_HELP_ABOUT                   33022
#define ID_GENERATE_SIGNIN              33023
#define ID_CONFIGURE_ALL_HALFSTAGE      33025
#define ID_CONFIGURE_ALL_BONUSES        33026
#define ID_CONFIGURE_ALL_SPRINTCL       33027
#define ID_CONFIGURE_ALL_POINTSCL       33028
#define ID_CONFIGURE_ALL_CLIMBCL        33029
#define ID_ANCHOR_OPENINNEWWINDOW       33031
#define ID_ANCHOR_OPEN                  33032
#define ID_ANCHOR_PRINTTARGET           33033
#define ID_ANCHOR_COPYSHORTCUT          33034
#define ID_ANCHOR_PROPERTIES            33035
#define ID_TOOLS_EXPORTTTWARE           33036
#define ID_VIEW_FONT_ZOOMIN             33037
#define ID_VIEW_FONT_ZOOMOUT            33038
#define ID_CONFIGURE_PROFILEPICKER      33039
#define ID_CONFIGURE_PROFILEPICKER_TOOLBAR 33040
#define ID_CONFIGURE_PROFILEPICKER_TOOLBAR1 33040
#define ID_BUTTON33041                  33041
#define ID_CONFIGURE_PROFILEPICKER_TOOLBAR2 33042
#define ID_VIEW_GRID                    33043
#define ID_VIEW_BARS                    33049
#define ID_SET                          33051
#define ID_EDIT_CLEANUPCOMPETITORS      33054
#define ID_GENERATE_BACKGROUND          33057
#define ID_VIEW_MONITORMODE             33059
#define ID_VIEW_ADDFILETOMONITOR        33060
#define ID_TOOLS_SERVER_PROCESSPENDING  33062
#define ID_TOOLS_SERVER_SENDTEAMS_CODE  33064
#define ID_TOOLS_SERVER_SENDTEAMS_NAME  33065
#define ID_INSERT_ORDERTEAMCAPTAINVEHICLES_ONSTAGECLASSIFICATION 33072
#define ID_INSERT_ORDERTEAMCAPTAINVEHICLES_ONGENERALCLASSIFICATION 33073
#define ID_BEELD_PREVIEW                33074
#define ID_VIEW_PREVIEW                 33075
#define ID_INSERT_PAGEBREAK             33076
#define ID_INSERT_ITEM                  33077
#define ID_EDIT_APPLYSTYLETOSELECTION_BOLD 33078
#define ID_EDIT_APPLYSTYLETOSELECTION_ITALIC 33079
#define ID_EDIT_APPLYSTYLETOSELECTION_UNDERLINED 33080
#define ID_INSERT_PARAGRAPHTITLE        33081
#define ID_EDIT_AUTONUMBER              33082
#define ID_CONFIGURE_ALL_MOSTAGGRESSIVECL 33084
#define ID_ARRIVAL_FUNCTIONS_INSERTPOSITION 33086
#define ID_ARRIVAL_FUNCTIONS_INSERTPOSITIONS 33087
#define ID_INDICATOR_KEY                59142
#define ID_INDICATOR_ACTIVEDOC          59143
#define ID_INDICATOR_MESSAGINGACTION    59144
#define ID_INDICATOR_DOCVERSION         59145
#define ID_INDICATOR_GENERATE           59146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        355
#define _APS_NEXT_COMMAND_VALUE         33088
#define _APS_NEXT_CONTROL_VALUE         1450
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
