// StageCalc.h: interface for the StageCalc class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_STAGECALC_H__E70F21FB_7D00_4CBE_A467_D8205A51B3E1__INCLUDED_)
#define AFX_STAGECALC_H__E70F21FB_7D00_4CBE_A467_D8205A51B3E1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CStageCalc  
{
public:
	static CString CommaValue(double f);
};

#endif // !defined(AFX_STAGECALC_H__E70F21FB_7D00_4CBE_A467_D8205A51B3E1__INCLUDED_)
