//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by srcalc.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SRCALC_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDC_INP1                        1000
#define IDC_INP2                        1001
#define IDC_RES1                        1002
#define IDC_INP3                        1003
#define IDC_PLUS                        1005
#define IDC_MINUS                       1006
#define IDC_CLEAR                       1007
#define IDC_OPERATION                   1010
#define IDC_ABOUT_NAME                  1013
#define IDC_ABOUT_VERSION               1014
#define IDC_EMAIL                       1164
#define IDC_WEBSITE                     1165

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
